version: "3.9"
services:
  api:
    build:
      context: .
    image: dsvistelnik/skypro_dsvistelnik_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID

    ports:
      - 80:81
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: flask_app_password
      POSTGRES_DB: flask_app

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5





