version: "3.9"
services:
  api:
    build:
      context: .
    image: dsvistelnik/skypro_dsvistelnik_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID

    ports:
      - 80:81
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5





