name: build and deploy app
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone project
        uses: actions/checkout@v2
      - name: prepare dotenv file
        run: cat .env_ci | envsubst > .env
      - name: prepare db file
        run: cat Dockerfile_ci | envsubst > Dockerfile
      - name: install requirements.txt
        run: pip install -r requirements.txt
      - name: use flake8 to check code style
        run: flake8 .
      - name: build image
        run: docker build -t dsvistelnik/skypro_dsvistelnik_app .
      - name: docker login
        run: echo ${{secrets.DOCKER_PASS_TOKEN}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: docker push
        run: docker push dsvistelnik/skypro_dsvistelnik_app

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone project
        uses: actions/checkout@v2
      - name: prepare docker-compose file
        run: cat docker-compose-ci.yaml | envsubst > docker-compose.yaml
      - name: copy docker-compose.yaml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_LOGIN}}
          password: ${{secrets.SERVER_PASS}}
          source: docker-compose.yaml
          target: sky_movies
      - name: start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_LOGIN}}
          password: ${{secrets.SERVER_PASS}}
          script: |
            cd sky_movies
            echo ${{secrets.SERVER_PASS}} | sudo -S docker compose up -d

