name: build and deploy app
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t dsvistelnik/skypro_dsvistelnik_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker push
        run: docker push dsvistelnik/skypro_dsvistelnik_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID


